# Generated by Django 3.0.5 on 2021-08-12 16:41

from django.db import migrations, models

import backend.recipes.validations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210809_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(validators=[backend.recipes.validations.ingredient_amount_valid]),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unigue_recipe_ingredient'),
        ),
    ]
